import express from "express";
import { createServer as createViteServer } from "vite";
import { google } from "googleapis";
import { OAuth2Client } from "google-auth-library";
import cookieSession from "cookie-session";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import { createClient } from "@supabase/supabase-js";
import bcrypt from "bcryptjs";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * GOOGLE SHEETS SETUP INSTRUCTIONS:
 * 1. Create a Google Cloud Project and enable Google Sheets API.
 * 2. Create a Service Account and download the JSON key file.
 * 3. Share your Google Sheet with the Service Account's email address (Editor access).
 * 4. Set the following environment variables in your Secrets panel:
 *    - GOOGLE_SHEET_ID: The ID from the sheet URL.
 *    - GOOGLE_SERVICE_ACCOUNT_EMAIL: The client_email from the JSON key.
 *    - GOOGLE_PRIVATE_KEY: The private_key from the JSON key (including BEGIN/END headers).
 *    - SUPABASE_URL: Your Supabase project URL or reference ID.
 *    - SUPABASE_ANON_KEY: Your Supabase project's anon/public key.
 *    - SUPABASE TABLE: beneficiary_details (columns: name, account_no, ifsc_code)
 * 
 * SUPABASE SQL TO CREATE TABLES:
 * -- 1. Users Table
 * CREATE TABLE users (
 *   id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
 *   first_name TEXT NOT NULL,
 *   last_name TEXT NOT NULL,
 *   email TEXT UNIQUE NOT NULL,
 *   password TEXT NOT NULL,
 *   units TEXT[] NOT NULL,
 *   role TEXT NOT NULL,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 2. Beneficiary Details Table
 * CREATE TABLE beneficiary_details (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT UNIQUE NOT NULL,
 *   account_no TEXT,
 *   ifsc_code TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 3. Orders Table
 * CREATE TABLE orders (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   timestamp TIMESTAMPTZ DEFAULT NOW(),
 *   email TEXT,
 *   unit TEXT,
 *   beneficiary_name TEXT,
 *   account_no TEXT,
 *   ifsc_code TEXT,
 *   bill_date DATE,
 *   due_date DATE,
 *   amount NUMERIC,
 *   approved_by_unit BOOLEAN DEFAULT FALSE,
 *   processed_by_finance BOOLEAN DEFAULT FALSE,
 *   payment_method TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- IMPORTANT: Disable RLS or add policies for these tables in Supabase Dashboard.
 * 
 * GOOGLE APPS SCRIPT EXAMPLE (Optional - if you want to use Apps Script):
 * function doPost(e) {
 *   var data = JSON.parse(e.postData.contents);
 *   var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Orders_Final");
 *   var timestamp = new Date();
 *   var rows = data.bills.map(function(bill) {
 *     return [timestamp, data.email, data.unit, data.beneficiaryName, data.accountNo, data.ifscCode, bill.billDate, bill.dueDate, bill.amount];
 *   });
 *   sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, 9).setValues(rows);
 *   return ContentService.createTextOutput(JSON.stringify({"success": true})).setMimeType(ContentService.MimeType.JSON);
 * }
 */

const app = express();
const PORT = 3000;

// Supabase configuration
const supabaseUrlRaw = process.env.SUPABASE_URL || "vgvnahcunvwigwaniejg";
const supabaseUrl = supabaseUrlRaw.includes("://") 
  ? supabaseUrlRaw 
  : `https://${supabaseUrlRaw}.supabase.co`;
const supabaseKey = process.env.SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndm5haGN1bnZ3aWd3YW5pZWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MDQ2MDgsImV4cCI6MjA4NzQ4MDYwOH0.qvv-O8mhmcpL1gDmP7kpd6mUzDvN1DZsqawy1KK2qCY";

const supabase = supabaseUrl && supabaseKey 
  ? createClient(supabaseUrl, supabaseKey)
  : null;

console.log(`Supabase URL: ${supabaseUrl}`);
console.log(`Supabase Key: ${supabaseKey ? supabaseKey.substring(0, 10) + "..." : "MISSING"}`);

if (!supabase) {
  console.warn("Supabase client failed to initialize. Check your credentials.");
}

// Google Sheets configuration
const GOOGLE_SHEET_ID = process.env.GOOGLE_SHEET_ID || "1dmWu8hdJrwsUE7nRChwVZ917sUiHYAz8gMAZ1uwyDgY";
const GOOGLE_SERVICE_ACCOUNT_EMAIL = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
const GOOGLE_PRIVATE_KEY = process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n");
const GOOGLE_SCRIPT_URL = process.env.GOOGLE_SCRIPT_URL || "https://script.google.com/macros/s/AKfycbyKJhtxHZuaNb-5QEX2EmW5uzegW71gHB5FmAd_u7nCQVNxuUpJWlHxoZ6yg6wc3pE8/exec";

const auth = (GOOGLE_SERVICE_ACCOUNT_EMAIL && GOOGLE_PRIVATE_KEY) 
  ? new google.auth.JWT({
      email: GOOGLE_SERVICE_ACCOUNT_EMAIL,
      key: GOOGLE_PRIVATE_KEY,
      scopes: ["https://www.googleapis.com/auth/spreadsheets"],
    })
  : null;

const ALL_UNITS = [
  "CKU", "WARP", "EMB", "HOOK & EYE", "TLU", "VAU", "CUP",
  "ALU", "MUM", "DMN", "ENH/ EHU", "DPU/ DPF", "APP", "LMN", "SUR", "SLU", "SUN", "TDU", "KDC", "Udhana", "BGU", "SGU", , "CAD",
];

app.use(express.json());

// Fetch customers from "Master Sheet"
app.get("/api/customers", async (req, res) => {
  if (!auth) return res.json([]);
  try {
    const sheets = google.sheets({ version: "v4", auth });
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: GOOGLE_SHEET_ID,
      range: "Master Sheet!A2:C", // Assuming Name, Account, IFSC
    });
    const rows = response.data.values || [];
    const customers = rows.map(row => ({
      name: row[0],
      account_no: row[1],
      ifsc_code: row[2]
    }));
    res.json(customers);
  } catch (error) {
    console.error("Error fetching customers from Master Sheet:", error);
    res.json([]);
  }
});

app.use(
  cookieSession({
    name: "session",
    keys: ["ginza-secret-key-v2"],
    maxAge: 24 * 60 * 60 * 1000, // 24 hours
    secure: true,
    sameSite: "none",
  })
);

// --- Auth Routes ---
app.post("/api/auth/register", async (req, res) => {
  const { firstName, lastName, email, password, units, role } = req.body;
  if (!supabase) return res.status(500).json({ error: "Supabase not configured" });

  try {
    const hashedPassword = await bcrypt.hash(password, 10);
    const { data, error } = await supabase
      .from("users")
      .insert([{ 
        first_name: firstName, 
        last_name: lastName, 
        email: email.toLowerCase(), 
        password: hashedPassword, 
        units, 
        role 
      }])
      .select()
      .single();

    if (error) throw error;
    res.json({ success: true });
  } catch (error: any) {
    res.status(400).json({ error: error.message });
  }
});

app.post("/api/auth/login", async (req, res) => {
  const { email, password } = req.body;
  if (!supabase) return res.status(500).json({ error: "Supabase not configured" });

  try {
    const { data: user, error } = await supabase
      .from("users")
      .select("*")
      .eq("email", email.toLowerCase())
      .single();

    if (error || !user) throw new Error("User not found");

    const isValid = await bcrypt.compare(password, user.password);
    if (!isValid) throw new Error("Invalid password");

    req.session!.user = {
      id: user.id,
      email: user.email,
      firstName: user.first_name,
      lastName: user.last_name,
      role: user.role,
      units: user.units
    };

    res.json({ user: req.session!.user });
  } catch (error: any) {
    res.status(401).json({ error: error.message });
  }
});

app.get("/api/auth/me", (req, res) => {
  res.json({ user: req.session?.user || null });
});

app.post("/api/auth/logout", (req, res) => {
  req.session = null;
  res.json({ success: true });
});

// API Routes
app.get("/api/units", (req, res) => {
  // Return all units regardless of email as requested
  res.json({ units: ALL_UNITS });
});

// Beneficiary Search Route (Search from Supabase and Google Sheet 'Master Sheet')
app.get("/api/beneficiaries/search", async (req, res) => {
  const name = req.query.name as string;
  if (!name || name.length < 2) {
    return res.json({ beneficiaries: [] });
  }

  let results: any[] = [];

  // 1. Try Supabase first as requested
  try {
    if (supabase) {
      const { data, error: sbError } = await supabase
        .from("beneficiary_details")
        .select("*")
        .ilike("name", `%${name}%`)
        .limit(10);
      
      if (!sbError && data) {
        results = data.map(b => ({
          name: b.name,
          account_no: b.account_no,
          ifsc_code: b.ifsc_code,
          source: "supabase"
        }));
      }
    }
  } catch (sbErr) {
    console.error("Supabase search error:", sbErr);
  }

  // 2. If results are few, try Google Sheets 'Master Sheet'
  if (results.length < 5) {
    try {
      const sheets = google.sheets({ version: "v4", auth });
      const response = await sheets.spreadsheets.values.get({
        spreadsheetId: GOOGLE_SHEET_ID,
        range: "Master Sheet!A:C",
      });

      const rows = response.data.values || [];
      if (rows.length > 1) {
        const dataRows = rows.slice(1);
        const searchLower = name.toLowerCase();

        const sheetResults = dataRows
          .filter(row => {
            const rowName = (row[0] || "").toString().toLowerCase();
            return rowName.includes(searchLower);
          })
          .map(row => ({
            name: row[0],
            account_no: row[1],
            ifsc_code: row[2],
            source: "sheets"
          }));

        // Merge and remove duplicates by name
        const existingNames = new Set(results.map(r => r.name.toLowerCase()));
        sheetResults.forEach(sr => {
          if (!existingNames.has(sr.name.toLowerCase())) {
            results.push(sr);
          }
        });
      }
    } catch (error: any) {
      console.error("Google Sheets search error:", error.message);
    }
  }

  res.json({ beneficiaries: results.slice(0, 10) });
});

// Form Submission Route
app.post("/api/submit", async (req, res) => {
  const { email, unit, beneficiaryName, accountNo, ifscCode, bills } = req.body;

  if (!email || !unit || !beneficiaryName || !accountNo || !ifscCode || !bills) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  try {
    // 1. Save to Supabase
    if (supabase) {
      // Robust Beneficiary Save: Try upsert, fallback to insert if constraint missing
      const { error: bError } = await supabase
        .from("beneficiary_details")
        .upsert({ name: beneficiaryName, account_no: accountNo, ifsc_code: ifscCode }, { onConflict: "name" });
      
      if (bError && bError.code !== '42P10') { // 42P10 is the missing constraint error
        console.error("Supabase Beneficiary Error:", bError);
        // If upsert fails due to constraint, we still try to proceed with the order
      }

      const supabaseOrders = bills.map((bill: any) => ({
        email,
        unit,
        beneficiary_name: beneficiaryName,
        account_no: accountNo,
        ifsc_code: ifscCode,
        bill_date: bill.billDate,
        due_date: bill.dueDate,
        amount: parseFloat(bill.amount),
        approved_by_unit: false,
        processed_by_finance: false
      }));
      
      const { error: oError } = await supabase.from("orders").insert(supabaseOrders);
      if (oError) {
        console.error("Supabase Orders Insert Error:", oError);
        throw new Error(`Order save failed: ${oError.message}`);
      }
    }

    // 2. Save to Google Sheet (Main Sheet)
    let sheetSaved = false;
    if (auth) {
      try {
        const sheets = google.sheets({ version: "v4", auth });
        const timestamp = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
        const rows = bills.map((bill: any) => [timestamp, email, unit, beneficiaryName, accountNo, ifscCode, bill.billDate, bill.dueDate, bill.amount, "Pending"]);
        await sheets.spreadsheets.values.append({
          spreadsheetId: GOOGLE_SHEET_ID,
          range: "Orders_Final!A:J",
          valueInputOption: "USER_ENTERED",
          requestBody: { values: rows },
        });
        console.log("Successfully appended to Google Sheets via API");
        sheetSaved = true;
      } catch (sheetError: any) {
        console.error("Google Sheets API Append Error:", sheetError);
      }
    }

    // Fallback to Google Script if API failed or not configured
    if (!sheetSaved && GOOGLE_SCRIPT_URL) {
      try {
        const response = await fetch(GOOGLE_SCRIPT_URL, {
          method: "POST",
          body: JSON.stringify({ email, unit, beneficiaryName, accountNo, ifscCode, bills }),
          headers: { "Content-Type": "application/json" }
        });
        const result = await response.json();
        if (result.success) {
          console.log("Successfully saved to Google Sheets via Script URL");
          sheetSaved = true;
        } else {
          console.error("Google Script Error:", result.error);
        }
      } catch (scriptError) {
        console.error("Google Script Fetch Error:", scriptError);
      }
    }

    if (!sheetSaved) {
      console.warn("Failed to save to Google Sheets via both API and Script.");
    }

    res.json({ success: true });
  } catch (error: any) {
    console.error("Submission Route Error:", error);
    res.status(500).json({ error: error.message || "Internal Server Error" });
  }
});

app.get("/api/orders", async (req, res) => {
  const { role, email } = req.session?.user || {};
  const { view } = req.query; // For Master: 'unit' or 'finance'
  if (!supabase) return res.json({ orders: [] });

  let query = supabase.from("orders").select("*");

  if (role === "Unit Team") {
    query = query.eq("email", email);
    // Filter by last 5 days for Unit Team history
    const fiveDaysAgo = new Date();
    fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);
    query = query.gte("created_at", fiveDaysAgo.toISOString());
  } else if (role === "Finance Team") {
    query = query.eq("approved_by_unit", true).eq("processed_by_finance", false);
  } else if (role === "Master") {
    if (view === "finance") {
      query = query.eq("approved_by_unit", true).eq("processed_by_finance", false);
    }
    // If view is 'unit' or not provided, show all
  }

  const { data, error } = await query.order("created_at", { ascending: false });
  res.json({ orders: data || [] });
});

app.post("/api/orders/approve", async (req, res) => {
  const { orderIds } = req.body;
  if (!supabase) return res.status(500).json({ error: "Supabase not configured" });

  const { error } = await supabase
    .from("orders")
    .update({ approved_by_unit: true })
    .in("id", orderIds);

  res.json({ success: !error });
});

app.post("/api/orders/process", async (req, res) => {
  const { orderIds, bank } = req.body; // bank: 'UBI' or 'SBI'
  if (!supabase) return res.status(500).json({ error: "Supabase not configured" });

  try {
    const { data: orders } = await supabase.from("orders").select("*").in("id", orderIds);
    if (!orders) throw new Error("No orders found");

    let sheetName = "";
    if (auth) {
      const sheets = google.sheets({ version: "v4", auth });
      sheetName = `${bank}_Payment_${Date.now()}`;

      // 1. Create new tab
      await sheets.spreadsheets.batchUpdate({
        spreadsheetId: GOOGLE_SHEET_ID,
        requestBody: {
          requests: [{ addSheet: { properties: { title: sheetName } } }]
        }
      });

      // 2. Prepare headers and data
      let headers: string[] = [];
      let rows: any[][] = [];

      if (bank === "UBI") {
        headers = ["Client Code", "Customer Reference No", "Debit Account No.", "Transaction Type Code", "Message Type", "Beneficiary ID", "Beneficiary Name", "Beneficiary Account No.", "Beneficiary Bank Swift Code / IFSC Code", "Payment Amount", "Value Date", "Remarks"];
        rows = orders.map(o => ["GINZA", o.id, "1234567890", "T", "M", o.beneficiary_name, o.beneficiary_name, o.account_no, o.ifsc_code, o.amount, o.bill_date, "Payment"]);
      } else {
        headers = ["SR NO", "Corp ID", "Customer Name", "Debit A/c No.", "Type", "Date of TXn", "Amount", "Beneficiery name", "IFSC CODE", "Beneficiery A/c No.", "Remark"];
        rows = orders.map((o, i) => [i + 1, "GINZA01", "GINZA INDUSTRIES", "0987654321", "NEFT", o.bill_date, o.amount, o.beneficiary_name, o.ifsc_code, o.account_no, "Payment"]);
      }

      await sheets.spreadsheets.values.update({
        spreadsheetId: GOOGLE_SHEET_ID,
        range: `${sheetName}!A1`,
        valueInputOption: "USER_ENTERED",
        requestBody: { values: [headers, ...rows] }
      });
    }

    // 3. Mark as processed in Supabase
    await supabase.from("orders").update({ processed_by_finance: true, payment_method: bank }).in("id", orderIds);

    res.json({ success: true, sheetName });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

app.get("/api/history", async (req, res) => {
  const email = req.query.email as string;
  if (!email) {
    return res.json({ orders: [] });
  }

  try {
    const sheets = google.sheets({ version: "v4", auth });
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: GOOGLE_SHEET_ID,
      range: "Sheet1!A:I",
    });

    const rows = response.data.values || [];
    if (rows.length <= 1) return res.json({ orders: [] });

    const headers = rows[0];
    const dataRows = rows.slice(1);

    // Filter by email and last 5 days
    const fiveDaysAgo = new Date();
    fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);

    const userOrders = dataRows
      .filter(row => {
        const rowEmail = row[1];
        const rowTimestamp = new Date(row[0]);
        return rowEmail === email && rowTimestamp >= fiveDaysAgo;
      })
      .map(row => ({
        timestamp: row[0],
        unit: row[2],
        beneficiary: row[3],
        account: row[4],
        amount: row[8],
      }))
      .reverse(); // Newest first

    res.json({ orders: userOrders });
  } catch (error) {
    console.error("History fetch error:", error);
    res.status(500).json({ error: "Failed to fetch history" });
  }
});

// Vite middleware for development
if (process.env.NODE_ENV !== "production") {
  const vite = await createViteServer({
    server: { middlewareMode: true },
    appType: "spa",
  });
  app.use(vite.middlewares);
} else {
  app.use(express.static(path.join(__dirname, "dist")));
  app.get("*", (req, res) => {
    res.sendFile(path.join(__dirname, "dist", "index.html"));
  });
}

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
