import express from "express";
import { createServer as createViteServer } from "vite";
import { google } from "googleapis";
import { OAuth2Client } from "google-auth-library";
import cookieSession from "cookie-session";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import { createClient } from "@supabase/supabase-js";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * GOOGLE SHEETS SETUP INSTRUCTIONS:
 * 1. Create a Google Cloud Project and enable Google Sheets API.
 * 2. Create a Service Account and download the JSON key file.
 * 3. Share your Google Sheet with the Service Account's email address (Editor access).
 * 4. Set the following environment variables in your Secrets panel:
 *    - GOOGLE_SHEET_ID: The ID from the sheet URL.
 *    - GOOGLE_SERVICE_ACCOUNT_EMAIL: The client_email from the JSON key.
 *    - GOOGLE_PRIVATE_KEY: The private_key from the JSON key (including BEGIN/END headers).
 *    - SUPABASE_URL: Your Supabase project URL or reference ID.
 *    - SUPABASE_ANON_KEY: Your Supabase project's anon/public key.
 *    - SUPABASE TABLE: beneficiary_details (columns: name, account_no, ifsc_code)
 * 
 * SUPABASE SQL TO CREATE TABLES:
 * -- 1. Beneficiary Details Table
 * CREATE TABLE beneficiary_details (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT UNIQUE NOT NULL,
 *   account_no TEXT,
 *   ifsc_code TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 2. Orders Table
 * CREATE TABLE orders (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   timestamp TIMESTAMPTZ DEFAULT NOW(),
 *   email TEXT,
 *   unit TEXT,
 *   beneficiary_name TEXT,
 *   account_no TEXT,
 *   ifsc_code TEXT,
 *   bill_date DATE,
 *   due_date DATE,
 *   amount NUMERIC,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- IMPORTANT: Disable RLS or add policies for these tables in Supabase Dashboard.
 * 
 * GOOGLE APPS SCRIPT EXAMPLE (Optional - if you want to use Apps Script):
 * function doPost(e) {
 *   var data = JSON.parse(e.postData.contents);
 *   var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Orders_Final");
 *   var timestamp = new Date();
 *   var rows = data.bills.map(function(bill) {
 *     return [timestamp, data.email, data.unit, data.beneficiaryName, data.accountNo, data.ifscCode, bill.billDate, bill.dueDate, bill.amount];
 *   });
 *   sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, 9).setValues(rows);
 *   return ContentService.createTextOutput(JSON.stringify({"success": true})).setMimeType(ContentService.MimeType.JSON);
 * }
 */

const app = express();
const PORT = 3000;

// Supabase configuration
const supabaseUrlRaw = process.env.SUPABASE_URL || "vgvnahcunvwigwaniejg";
const supabaseUrl = supabaseUrlRaw.includes("://") 
  ? supabaseUrlRaw 
  : `https://${supabaseUrlRaw}.supabase.co`;
const supabaseKey = process.env.SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndm5haGN1bnZ3aWd3YW5pZWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MDQ2MDgsImV4cCI6MjA4NzQ4MDYwOH0.qvv-O8mhmcpL1gDmP7kpd6mUzDvN1DZsqawy1KK2qCY";

const supabase = supabaseUrl && supabaseKey 
  ? createClient(supabaseUrl, supabaseKey)
  : null;

console.log(`Supabase URL: ${supabaseUrl}`);
console.log(`Supabase Key: ${supabaseKey ? supabaseKey.substring(0, 10) + "..." : "MISSING"}`);

if (!supabase) {
  console.warn("Supabase client failed to initialize. Check your credentials.");
}

// Google Sheets configuration
const GOOGLE_SHEET_ID = process.env.GOOGLE_SHEET_ID || "1dmWu8hdJrwsUE7nRChwVZ917sUiHYAz8gMAZ1uwyDgY";
const GOOGLE_SERVICE_ACCOUNT_EMAIL = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
const GOOGLE_PRIVATE_KEY = process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n");
const GOOGLE_SCRIPT_URL = process.env.GOOGLE_SCRIPT_URL || "https://script.google.com/macros/s/AKfycbyKJhtxHZuaNb-5QEX2EmW5uzegW71gHB5FmAd_u7nCQVNxuUpJWlHxoZ6yg6wc3pE8/exec";

const auth = new google.auth.JWT({
  email: GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: GOOGLE_PRIVATE_KEY,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

// Unit Mapping Data
const UNIT_MAPPING: Record<string, string[]> = {
  "thanu.pillai@ginzalimited.com": ["ALU"],
  "ashok.sethia@ginzalimited.com": ["MUM"],
  "mahendra.sharma@ginzalimited.com": ["DMN"],
  "vinod.mahnot@ginzalimited.com": ["TLU"],
  "amrit.daga@ginzalimited.com": ["ENH/ EHU"],
  "ankit.jain@ginzalimited.com": ["DPU/ DPN"],
  "lalit.jain@ginzalimited.com": ["APP"],
  "mohit.maloo@ginzalimited.com": ["LMN/VAU"],
  "shashikant.maloo@ginzalimited.com": ["CKU", "SAC"],
  "tejkaran.dugar@ginzalimited.com": ["SUR"],
  "piyush.samsukha@ginzalimited.com": ["EMB"],
  "sanjay.nahata@ginzalimited.com": ["SLU"],
  "piyush.daga@ginzalimited.com": ["SUN"],
  "etusurat@ginzalimited.com": ["TDU"],
  "piyush.baid@ginzalimited.com": ["KDC", "Udhana"],
  "amit.rout@ginzalimited.com": ["BGU", "SGU"],
  "alok.sancheti@ginzalimited.com": ["CPP"],
  "srmandal@ginzalimited.com": ["IT"],
  "dharmesh.rana@ginzalimited.com": ["CAD"],
  "ahmedabad@ginzalimited.com": ["AHEMDABAD"],
  "rajesh.jain@ginzalimited.com": ["KOLKATTA"],
  "vinay.chhajer@ginzalimited.com": ["DELHI"],
  "murali.krishna@ginzalimited.com": ["BENGALURU"],
  "tirupur@ginzalimited.com": ["TIRUPUR"],
  "sachin.bhosle@ginzalimited.com": ["ULHASNAGAR"],
};

app.use(express.json());
app.use(
  cookieSession({
    name: "session",
    keys: ["ginza-secret-key"],
    maxAge: 24 * 60 * 60 * 1000, // 24 hours
    secure: true,
    sameSite: "none",
  })
);

// API Routes
app.get("/api/units", (req, res) => {
  const email = req.query.email as string;
  if (!email) {
    return res.json({ units: [] });
  }
  const units = UNIT_MAPPING[email.toLowerCase()] || [];
  res.json({ units });
});

// Debug Supabase connection
app.get("/api/debug/supabase", async (req, res) => {
  if (!supabase) {
    return res.json({ status: "error", message: "Supabase client not initialized" });
  }
  try {
    // Try to get one row to see columns
    const { data, error } = await supabase.from("beneficiary_details").select("*").limit(1);
    if (error) {
      return res.json({ status: "error", error, message: "Check if table 'beneficiary_details' exists" });
    }
    const columns = data && data.length > 0 ? Object.keys(data[0]) : "No data to determine columns";
    res.json({ status: "ok", data, columns });
  } catch (err: any) {
    res.json({ status: "error", message: err.message });
  }
});

// Beneficiary Search Route
app.get("/api/beneficiaries/search", async (req, res) => {
  const name = req.query.name as string;
  if (!name || name.length < 2) {
    return res.json({ beneficiaries: [] });
  }

  try {
    if (!supabase) {
      console.error("Search attempted but Supabase client is null");
      return res.json({ beneficiaries: [] });
    }
    console.log(`Searching for beneficiary: ${name}`);
    const { data, error } = await supabase
      .from("beneficiary_details")
      .select("*")
      .ilike("name", `%${name}%`)
      .limit(5);

    if (error) {
      console.error("Supabase query error:", error);
      throw error;
    }
    console.log(`Found ${data?.length || 0} suggestions`);
    res.json({ beneficiaries: data || [] });
  } catch (error) {
    console.error("Beneficiary search error:", error);
    res.status(500).json({ error: "Failed to search beneficiaries" });
  }
});

app.get("/api/history", async (req, res) => {
  const email = req.query.email as string;
  if (!email) {
    return res.json({ orders: [] });
  }

  try {
    const sheets = google.sheets({ version: "v4", auth });
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: GOOGLE_SHEET_ID,
      range: "Sheet1!A:I",
    });

    const rows = response.data.values || [];
    if (rows.length <= 1) return res.json({ orders: [] });

    const headers = rows[0];
    const dataRows = rows.slice(1);

    // Filter by email and last 5 days
    const fiveDaysAgo = new Date();
    fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);

    const userOrders = dataRows
      .filter(row => {
        const rowEmail = row[1];
        const rowTimestamp = new Date(row[0]);
        return rowEmail === email && rowTimestamp >= fiveDaysAgo;
      })
      .map(row => ({
        timestamp: row[0],
        unit: row[2],
        beneficiary: row[3],
        account: row[4],
        amount: row[8],
      }))
      .reverse(); // Newest first

    res.json({ orders: userOrders });
  } catch (error) {
    console.error("History fetch error:", error);
    res.status(500).json({ error: "Failed to fetch history" });
  }
});

// Form Submission Route
app.post("/api/submit", async (req, res) => {
  const { email, unit, beneficiaryName, accountNo, ifscCode, bills } = req.body;

  if (!email || !unit || !beneficiaryName || !accountNo || !ifscCode || !bills) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  try {
    let submittedToSheets = false;

    // 1. Try Google Apps Script if URL is provided
    if (GOOGLE_SCRIPT_URL) {
      try {
        console.log(`Attempting submission via Google Apps Script: ${GOOGLE_SCRIPT_URL}`);
        const scriptRes = await fetch(GOOGLE_SCRIPT_URL, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email, unit, beneficiaryName, accountNo, ifscCode, bills }),
        });
        
        if (!scriptRes.ok) {
          throw new Error(`HTTP error! status: ${scriptRes.status}`);
        }

        const scriptData = await scriptRes.json();
        if (scriptData.success) {
          console.log("Successfully submitted via Google Apps Script");
          submittedToSheets = true;
        } else {
          console.error("Google Apps Script returned success:false:", scriptData.error);
        }
      } catch (scriptErr: any) {
        console.error("Failed to call Google Apps Script:", scriptErr.message);
      }
    }

    // 2. Fallback to Service Account if not already submitted and credentials exist
    if (!submittedToSheets && GOOGLE_SERVICE_ACCOUNT_EMAIL && GOOGLE_PRIVATE_KEY) {
      try {
        console.log("Attempting submission via Google Service Account");
        const sheets = google.sheets({ version: "v4", auth });

        const timestamp = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
        const rows = bills.map((bill: any) => [
          timestamp,
          email,
          unit,
          beneficiaryName,
          accountNo,
          ifscCode,
          bill.billDate,
          bill.dueDate,
          bill.amount,
        ]);

        await sheets.spreadsheets.values.append({
          spreadsheetId: GOOGLE_SHEET_ID,
          range: "Orders_Final!A:I",
          valueInputOption: "USER_ENTERED",
          requestBody: {
            values: rows,
          },
        });
        submittedToSheets = true;
        console.log("Successfully submitted via Google Service Account");
      } catch (sheetsErr: any) {
        console.error("Google Sheets Service Account error:", sheetsErr.message);
      }
    }

    if (!submittedToSheets) {
      console.warn("Could not save to Google Sheets (both Script URL and Service Account failed or were missing).");
    }

    // 3. Always save to Supabase
    try {
      if (supabase) {
        // 1. Update/Insert Beneficiary Details
        await supabase
          .from("beneficiary_details")
          .upsert(
            { name: beneficiaryName, account_no: accountNo, ifsc_code: ifscCode },
            { onConflict: "name" }
          );

        // 2. Save Order Data to Supabase
        const supabaseOrders = bills.map((bill: any) => ({
          email,
          unit,
          beneficiary_name: beneficiaryName,
          account_no: accountNo,
          ifsc_code: ifscCode,
          bill_date: bill.billDate,
          due_date: bill.dueDate,
          amount: parseFloat(bill.amount),
        }));

        const { error: sbOrderError } = await supabase
          .from("orders")
          .insert(supabaseOrders);
        
        if (sbOrderError) console.error("Supabase order insert error:", sbOrderError);
      }
    } catch (sbError) {
      console.error("Supabase general error:", sbError);
    }

    res.json({ success: true });
  } catch (error: any) {
    console.error("Submission error details:", error);
    const message = error.message || "Unknown error";
    res.status(500).json({ 
      error: `Failed to submit data: ${message}. 1. Check if sheet 'Orders_Final' exists. 2. Ensure Service Account is an 'Editor' on the sheet.` 
    });
  }
});

// Vite middleware for development
if (process.env.NODE_ENV !== "production") {
  const vite = await createViteServer({
    server: { middlewareMode: true },
    appType: "spa",
  });
  app.use(vite.middlewares);
} else {
  app.use(express.static(path.join(__dirname, "dist")));
  app.get("*", (req, res) => {
    res.sendFile(path.join(__dirname, "dist", "index.html"));
  });
}

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
